services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        INSTALL_XDEBUG: "true"
    container_name: francascc25_php
    restart: unless-stopped
    ports:
      - "8001:8080"             # Le dockerfile expose le port 8080
    volumes:
      - ./:/app
    environment:
      APP_ENV: dev
      SERVER_NAME: :8080
      CADDY_MERCURE: "off"
      XDEBUG_MODE: "debug"      # active avec XDEBUG_MODE=debug
    depends_on:
      - db
    networks:
      - francascc25

  # Base de données MariaDB
  db:
    image: mariadb:10.11.2
    container_name: francascc25_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=francas2025_db
      - MYSQL_USER=xavier
      - MYSQL_PASSWORD=Corwin_40280
      - MYSQL_ROOT_PASSWORD=Corwin_40280
    ports:
      - "3307:3306"
    volumes:
      - .docker/db_data:/var/lib/mysql

  # phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: francascc25_pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=Corwin_40280
    depends_on:
      - db

networks:
  symfony:
