services:

  php:
    build: .
    container_name: francascc25_php
    restart: unless-stopped
    ports:
      - "80:80"
    #  - "443:443"
    #  - "443:443/udp"
    volumes:
      - ./:/app
    environment:
      - SERVER_NAME=:80
    depends_on:
      - db
    networks:
      - francascc25

  # Base de données MariaDB
  db:
    image: mariadb:10.11.2
    container_name: francascc25_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=francas2025_db
      - MYSQL_USER=xavier
      - MYSQL_PASSWORD=Corwin_40280
      - MYSQL_ROOT_PASSWORD=Corwin_40280
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - francascc25

  # phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: francascc25_pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=Corwin_40280
    depends_on:
      - db
    networks:
      - francascc25

volumes:
  db_data:

networks:
  francascc25:
    external: true
